common: &common
    adapter: postgresql
    username: <%= ENV['USER'] %>
    password: <%= ENV['PG_PASS'] %>

development:
    <<: *common
    database: yorker_development

test:
    <<: *common
    database: yorker_test

production:
    <<: *common
    database: yorker_production

# this is a special environment using sqlite, for people without
# package managers
demo:
    adapter: sqlite3
    database: db/yorker_demo.sqlite3

