common: &common
    adapter: postgresql
    username: <%= ENV['USER'] %>

development:
    <<: *common
    database: yorker_development

test:
    <<: *common
    database: yorker_test

production:
    <<: *common
    database: yorker_production

