common: &common
    adapter: postgresql
    username: <%= ENV['USER'] %>
    password: <%= ENV['PG_PASS'] %>

development:
    <<: *common
    database: yorker_development

test:
    <<: *common
    database: yorker_test

production:
    <<: *common
    database: yorker_production

