common: &common
    adapter: postgresql
    username: <%= ENV['USER'] %>
    encoding: utf-8

development:
    <<: *common
    database: yorker_development

test:
    adapter: sqlite3
    database: db/yorker_test.sqlite3

production:
    <<: *common
    database: yorker_production

staging:
    <<: *common
    database: yorker_staging

# this is a special environment using sqlite, for people without
# package managers
demo:
    adapter: sqlite3
    database: db/yorker_demo.sqlite3

